name: nour
description: "NOUR — Le Jeu. RPG mobile pixel art : apprendre, agir dans la vraie vie, progresser."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.3
  firebase_core: ^4.14.0
  firebase_auth: ^6.6.1
  cloud_firestore: ^6.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  yaml: ^3.1.3
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/bg/
    - assets/pixel/sprites.json
    - assets/pixel/characters/protagonist/
    - assets/pixel/characters/noura/
    - assets/pixel/characters/npcs/
    - assets/pixel/enemies/waswas/
    - assets/pixel/enemies/grand_waswas/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/bg/logo-nour.png"
